#!/bin/sh -e

#Get version string
version=$(echo "$2" | awk '{print $1}')

echo "Moving sources..."
mkdir -p $1/usr/src

tar xf linux-$version.tar.xz?no-extract
mv linux-$version.tar.xz?no-extract $1/usr/src/linux-$version.tar.xz
